### ISSUE TITLE
New Work flow request for Sophos Central Cloud

### ISSUE THREAD

**Issue by satiskumark** [IBM/IBM-QRadar-Universal-Cloud-REST-API#32]
Hello...

Can someone help on getting on wirk flow for Sophos central.. 
I have informed that I can only API token and keys alone...
From Sophos article python script is only available, for SIEM integration..

**Comment by dpdoherty** [comment]
Hi @satiskumark did you ever get the Sophos Cloud data ingested to Qradar? 
@ChrisCollinsIBM is there instructions how to use the Sophos_workflow.xml and Sophos_workflow.parameter.values.xml

**Comment by ChrisCollinsIBM** [comment]
Hi @dpdoherty, the link to the Universal Cloud REST API docs is here:

https://www.ibm.com/docs/en/dsm?topic=configuration-universal-cloud-rest-api-protocol

So that's how you configure a log source using these provided values.

If that's not what you're looking for, but more wondering how you get the values required by the `Sophos_workflow.parameter.values.xml` file (which is what contains the config -  the workflow itself shouldn't need any editing) then the original contributors may be able to assist.

**Comment by ChrisCollinsIBM** [comment]
Closing out due to inactivity. Please re-open and reach out to the original contributor @sivaranjinipanneerselvam with any questions.
