### ISSUE TITLE
MCAS Workflow Error

### ISSUE THREAD

**Issue by chrisneed1** [IBM/IBM-QRadar-Universal-Cloud-REST-API#72]
Using the MCAS Workflow the log source has gone into error with the following message:

`/activity_logs/response/body/data is not valid`

I am receiving some activity events however these are sporadic and attempting to verify against the MCAS console show a lot have been missed.

**Comment by chrisneed1** [comment]
Could it be a volume thing?  The log source could be pulling anywhere from 20-35k activity events every 10 mins depending on the time of day.

**Comment by MORichardsIBM** [comment]
Hi Chrisneed1, 
This error means the workflow was trying to look in the /data section of the JSON response but it didn't contain any events, but it was either not present / not in the proper format or something to that effect. I would recommend using the CLI Testing tool with verbose mode, -v, to see the output and possibly deduce what is happening (https://www.ibm.com/docs/en/dsm?topic=protocol-command-line-testing-tool).

Please report back any errors (and obfuscate any and all personal information, hostnames, or identifying information from the record) so that we can review them.

**Comment by ChrisCollinsIBM** [comment]
Did you get this sorted out @chrisneed1? I'll close this out soon if there's no update but feel free to re-open.

**Comment by maximpoleley** [comment]
@ChrisCollinsIBM Could you say is there a way to check if data exists before accessing it?

**Comment by ChrisCollinsIBM** [comment]
Since /activity_logs/response/body/data is what is "invalid" in the error you could probably check that body exists first or is not null.

For example:
` <If condition="/activity_logs/response/body != null" >`
And also after that
` <If condition="/activity_logs/response/body/data != null" >`

Or something to that regard.

**Comment by maximpoleley** [comment]
> Since /activity_logs/response/body/data is what is "invalid" in the error you could probably check that body exists first or is not null.
> 
> For example: ` <If condition="/activity_logs/response/body != null" >` And also after that ` <If condition="/activity_logs/response/body/data != null" >`
> 
> Or something to that regard.

Could you please take a lookt at https://github.com/ibm-security-intelligence/IBM-QRadar-Universal-Cloud-REST-API/issues/88 ?

**Comment by ChrisCollinsIBM** [comment]
No response from @chrisneed1 on this so closing out for the time being, but some suggestions have been posted that I think will help resolve the issue. Please re-open if needed.
